/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /tmp/buildd/ros-hydro-app-manager-1.0.3-0precise-20150707-1324/msg/StatusCodes.msg
 *
 */


#ifndef APP_MANAGER_MESSAGE_STATUSCODES_H
#define APP_MANAGER_MESSAGE_STATUSCODES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace app_manager
{
template <class ContainerAllocator>
struct StatusCodes_
{
  typedef StatusCodes_<ContainerAllocator> Type;

  StatusCodes_()
    {
    }
  StatusCodes_(const ContainerAllocator& _alloc)
    {
    }




    enum { SUCCESS = 0 };
     enum { BAD_REQUEST = 400 };
     enum { NOT_FOUND = 404 };
     enum { NOT_RUNNING = 430 };
     enum { INTERNAL_ERROR = 500 };
     enum { APP_INVALID = 510 };
     enum { MULTIAPP_NOT_SUPPORTED = 511 };
 

  typedef boost::shared_ptr< ::app_manager::StatusCodes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::app_manager::StatusCodes_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct StatusCodes_

typedef ::app_manager::StatusCodes_<std::allocator<void> > StatusCodes;

typedef boost::shared_ptr< ::app_manager::StatusCodes > StatusCodesPtr;
typedef boost::shared_ptr< ::app_manager::StatusCodes const> StatusCodesConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::app_manager::StatusCodes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::app_manager::StatusCodes_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace app_manager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'app_manager': ['/tmp/buildd/ros-hydro-app-manager-1.0.3-0precise-20150707-1324/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::app_manager::StatusCodes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::app_manager::StatusCodes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::app_manager::StatusCodes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::app_manager::StatusCodes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::app_manager::StatusCodes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::app_manager::StatusCodes_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::app_manager::StatusCodes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f286aed2b2ab4b227e7b7185bae624d";
  }

  static const char* value(const ::app_manager::StatusCodes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f286aed2b2ab4b2ULL;
  static const uint64_t static_value2 = 0x27e7b7185bae624dULL;
};

template<class ContainerAllocator>
struct DataType< ::app_manager::StatusCodes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "app_manager/StatusCodes";
  }

  static const char* value(const ::app_manager::StatusCodes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::app_manager::StatusCodes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Common error codes used with App Manager.\n\
int32 SUCCESS = 0\n\
# Request was invalid.\n\
int32 BAD_REQUEST = 400\n\
# App is not installed.\n\
int32 NOT_FOUND = 404\n\
# App is not running.\n\
int32 NOT_RUNNING = 430\n\
# Unknown internal error on the server.\n\
int32 INTERNAL_ERROR = 500\n\
# App is installed but failed validation.\n\
int32 APP_INVALID = 510\n\
# App manager does not support launching multiple apps simultaneously. Running app must first be stopped.\n\
int32 MULTIAPP_NOT_SUPPORTED = 511\n\
";
  }

  static const char* value(const ::app_manager::StatusCodes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::app_manager::StatusCodes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct StatusCodes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::app_manager::StatusCodes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::app_manager::StatusCodes_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // APP_MANAGER_MESSAGE_STATUSCODES_H
