/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /tmp/buildd/ros-hydro-app-manager-1.0.3-0precise-20150707-1324/srv/UninstallApp.srv
 *
 */


#ifndef APP_MANAGER_MESSAGE_UNINSTALLAPP_H
#define APP_MANAGER_MESSAGE_UNINSTALLAPP_H

#include <ros/service_traits.h>


#include <app_manager/UninstallAppRequest.h>
#include <app_manager/UninstallAppResponse.h>


namespace app_manager
{

struct UninstallApp
{

typedef UninstallAppRequest Request;
typedef UninstallAppResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UninstallApp
} // namespace app_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::app_manager::UninstallApp > {
  static const char* value()
  {
    return "1694b710073aaad53ae6c852885793c6";
  }

  static const char* value(const ::app_manager::UninstallApp&) { return value(); }
};

template<>
struct DataType< ::app_manager::UninstallApp > {
  static const char* value()
  {
    return "app_manager/UninstallApp";
  }

  static const char* value(const ::app_manager::UninstallApp&) { return value(); }
};


// service_traits::MD5Sum< ::app_manager::UninstallAppRequest> should match 
// service_traits::MD5Sum< ::app_manager::UninstallApp > 
template<>
struct MD5Sum< ::app_manager::UninstallAppRequest>
{
  static const char* value()
  {
    return MD5Sum< ::app_manager::UninstallApp >::value();
  }
  static const char* value(const ::app_manager::UninstallAppRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::app_manager::UninstallAppRequest> should match 
// service_traits::DataType< ::app_manager::UninstallApp > 
template<>
struct DataType< ::app_manager::UninstallAppRequest>
{
  static const char* value()
  {
    return DataType< ::app_manager::UninstallApp >::value();
  }
  static const char* value(const ::app_manager::UninstallAppRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::app_manager::UninstallAppResponse> should match 
// service_traits::MD5Sum< ::app_manager::UninstallApp > 
template<>
struct MD5Sum< ::app_manager::UninstallAppResponse>
{
  static const char* value()
  {
    return MD5Sum< ::app_manager::UninstallApp >::value();
  }
  static const char* value(const ::app_manager::UninstallAppResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::app_manager::UninstallAppResponse> should match 
// service_traits::DataType< ::app_manager::UninstallApp > 
template<>
struct DataType< ::app_manager::UninstallAppResponse>
{
  static const char* value()
  {
    return DataType< ::app_manager::UninstallApp >::value();
  }
  static const char* value(const ::app_manager::UninstallAppResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // APP_MANAGER_MESSAGE_UNINSTALLAPP_H
