/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /tmp/buildd/ros-hydro-zeroconf-msgs-0.2.1-0precise-20150326-2047/srv/ListDiscoveredServices.srv
 *
 */


#ifndef ZEROCONF_MSGS_MESSAGE_LISTDISCOVEREDSERVICES_H
#define ZEROCONF_MSGS_MESSAGE_LISTDISCOVEREDSERVICES_H

#include <ros/service_traits.h>


#include <zeroconf_msgs/ListDiscoveredServicesRequest.h>
#include <zeroconf_msgs/ListDiscoveredServicesResponse.h>


namespace zeroconf_msgs
{

struct ListDiscoveredServices
{

typedef ListDiscoveredServicesRequest Request;
typedef ListDiscoveredServicesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ListDiscoveredServices
} // namespace zeroconf_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::zeroconf_msgs::ListDiscoveredServices > {
  static const char* value()
  {
    return "5e4f7a51e03f794adcd5dbfc4a5acfb6";
  }

  static const char* value(const ::zeroconf_msgs::ListDiscoveredServices&) { return value(); }
};

template<>
struct DataType< ::zeroconf_msgs::ListDiscoveredServices > {
  static const char* value()
  {
    return "zeroconf_msgs/ListDiscoveredServices";
  }

  static const char* value(const ::zeroconf_msgs::ListDiscoveredServices&) { return value(); }
};


// service_traits::MD5Sum< ::zeroconf_msgs::ListDiscoveredServicesRequest> should match 
// service_traits::MD5Sum< ::zeroconf_msgs::ListDiscoveredServices > 
template<>
struct MD5Sum< ::zeroconf_msgs::ListDiscoveredServicesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::zeroconf_msgs::ListDiscoveredServices >::value();
  }
  static const char* value(const ::zeroconf_msgs::ListDiscoveredServicesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::zeroconf_msgs::ListDiscoveredServicesRequest> should match 
// service_traits::DataType< ::zeroconf_msgs::ListDiscoveredServices > 
template<>
struct DataType< ::zeroconf_msgs::ListDiscoveredServicesRequest>
{
  static const char* value()
  {
    return DataType< ::zeroconf_msgs::ListDiscoveredServices >::value();
  }
  static const char* value(const ::zeroconf_msgs::ListDiscoveredServicesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::zeroconf_msgs::ListDiscoveredServicesResponse> should match 
// service_traits::MD5Sum< ::zeroconf_msgs::ListDiscoveredServices > 
template<>
struct MD5Sum< ::zeroconf_msgs::ListDiscoveredServicesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::zeroconf_msgs::ListDiscoveredServices >::value();
  }
  static const char* value(const ::zeroconf_msgs::ListDiscoveredServicesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::zeroconf_msgs::ListDiscoveredServicesResponse> should match 
// service_traits::DataType< ::zeroconf_msgs::ListDiscoveredServices > 
template<>
struct DataType< ::zeroconf_msgs::ListDiscoveredServicesResponse>
{
  static const char* value()
  {
    return DataType< ::zeroconf_msgs::ListDiscoveredServices >::value();
  }
  static const char* value(const ::zeroconf_msgs::ListDiscoveredServicesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ZEROCONF_MSGS_MESSAGE_LISTDISCOVEREDSERVICES_H
