/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /tmp/buildd/ros-hydro-dynamic-reconfigure-1.5.37-0precise-20150329-1440/srv/Reconfigure.srv
 *
 */


#ifndef DYNAMIC_RECONFIGURE_MESSAGE_RECONFIGURE_H
#define DYNAMIC_RECONFIGURE_MESSAGE_RECONFIGURE_H

#include <ros/service_traits.h>


#include <dynamic_reconfigure/ReconfigureRequest.h>
#include <dynamic_reconfigure/ReconfigureResponse.h>


namespace dynamic_reconfigure
{

struct Reconfigure
{

typedef ReconfigureRequest Request;
typedef ReconfigureResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Reconfigure
} // namespace dynamic_reconfigure


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamic_reconfigure::Reconfigure > {
  static const char* value()
  {
    return "bb125d226a21982a4a98760418dc2672";
  }

  static const char* value(const ::dynamic_reconfigure::Reconfigure&) { return value(); }
};

template<>
struct DataType< ::dynamic_reconfigure::Reconfigure > {
  static const char* value()
  {
    return "dynamic_reconfigure/Reconfigure";
  }

  static const char* value(const ::dynamic_reconfigure::Reconfigure&) { return value(); }
};


// service_traits::MD5Sum< ::dynamic_reconfigure::ReconfigureRequest> should match 
// service_traits::MD5Sum< ::dynamic_reconfigure::Reconfigure > 
template<>
struct MD5Sum< ::dynamic_reconfigure::ReconfigureRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamic_reconfigure::Reconfigure >::value();
  }
  static const char* value(const ::dynamic_reconfigure::ReconfigureRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamic_reconfigure::ReconfigureRequest> should match 
// service_traits::DataType< ::dynamic_reconfigure::Reconfigure > 
template<>
struct DataType< ::dynamic_reconfigure::ReconfigureRequest>
{
  static const char* value()
  {
    return DataType< ::dynamic_reconfigure::Reconfigure >::value();
  }
  static const char* value(const ::dynamic_reconfigure::ReconfigureRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamic_reconfigure::ReconfigureResponse> should match 
// service_traits::MD5Sum< ::dynamic_reconfigure::Reconfigure > 
template<>
struct MD5Sum< ::dynamic_reconfigure::ReconfigureResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamic_reconfigure::Reconfigure >::value();
  }
  static const char* value(const ::dynamic_reconfigure::ReconfigureResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamic_reconfigure::ReconfigureResponse> should match 
// service_traits::DataType< ::dynamic_reconfigure::Reconfigure > 
template<>
struct DataType< ::dynamic_reconfigure::ReconfigureResponse>
{
  static const char* value()
  {
    return DataType< ::dynamic_reconfigure::Reconfigure >::value();
  }
  static const char* value(const ::dynamic_reconfigure::ReconfigureResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIC_RECONFIGURE_MESSAGE_RECONFIGURE_H
