/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /tmp/buildd/ros-hydro-nodelet-1.8.6-0precise-20150329-0144/srv/NodeletList.srv
 *
 */


#ifndef NODELET_MESSAGE_NODELETLIST_H
#define NODELET_MESSAGE_NODELETLIST_H

#include <ros/service_traits.h>


#include <nodelet/NodeletListRequest.h>
#include <nodelet/NodeletListResponse.h>


namespace nodelet
{

struct NodeletList
{

typedef NodeletListRequest Request;
typedef NodeletListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NodeletList
} // namespace nodelet


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nodelet::NodeletList > {
  static const char* value()
  {
    return "99c7b10e794f5600b8030e697e946ca7";
  }

  static const char* value(const ::nodelet::NodeletList&) { return value(); }
};

template<>
struct DataType< ::nodelet::NodeletList > {
  static const char* value()
  {
    return "nodelet/NodeletList";
  }

  static const char* value(const ::nodelet::NodeletList&) { return value(); }
};


// service_traits::MD5Sum< ::nodelet::NodeletListRequest> should match 
// service_traits::MD5Sum< ::nodelet::NodeletList > 
template<>
struct MD5Sum< ::nodelet::NodeletListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nodelet::NodeletList >::value();
  }
  static const char* value(const ::nodelet::NodeletListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodelet::NodeletListRequest> should match 
// service_traits::DataType< ::nodelet::NodeletList > 
template<>
struct DataType< ::nodelet::NodeletListRequest>
{
  static const char* value()
  {
    return DataType< ::nodelet::NodeletList >::value();
  }
  static const char* value(const ::nodelet::NodeletListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nodelet::NodeletListResponse> should match 
// service_traits::MD5Sum< ::nodelet::NodeletList > 
template<>
struct MD5Sum< ::nodelet::NodeletListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nodelet::NodeletList >::value();
  }
  static const char* value(const ::nodelet::NodeletListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nodelet::NodeletListResponse> should match 
// service_traits::DataType< ::nodelet::NodeletList > 
template<>
struct DataType< ::nodelet::NodeletListResponse>
{
  static const char* value()
  {
    return DataType< ::nodelet::NodeletList >::value();
  }
  static const char* value(const ::nodelet::NodeletListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODELET_MESSAGE_NODELETLIST_H
