"""autogenerated by genpy from clearpath_base/DifferentialControl.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class DifferentialControl(genpy.Message):
  _md5sum = "ae0672163e13fc0bb6491960c53a3259"
  _type = "clearpath_base/DifferentialControl"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
float64 l_p
float64 l_i
float64 l_d
float64 l_ffwd
float64 l_stic
float64 l_sat
float64 r_p
float64 r_i
float64 r_d
float64 r_ffwd
float64 r_stic
float64 r_sat

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

"""
  __slots__ = ['header','l_p','l_i','l_d','l_ffwd','l_stic','l_sat','r_p','r_i','r_d','r_ffwd','r_stic','r_sat']
  _slot_types = ['std_msgs/Header','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,l_p,l_i,l_d,l_ffwd,l_stic,l_sat,r_p,r_i,r_d,r_ffwd,r_stic,r_sat

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DifferentialControl, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.l_p is None:
        self.l_p = 0.
      if self.l_i is None:
        self.l_i = 0.
      if self.l_d is None:
        self.l_d = 0.
      if self.l_ffwd is None:
        self.l_ffwd = 0.
      if self.l_stic is None:
        self.l_stic = 0.
      if self.l_sat is None:
        self.l_sat = 0.
      if self.r_p is None:
        self.r_p = 0.
      if self.r_i is None:
        self.r_i = 0.
      if self.r_d is None:
        self.r_d = 0.
      if self.r_ffwd is None:
        self.r_ffwd = 0.
      if self.r_stic is None:
        self.r_stic = 0.
      if self.r_sat is None:
        self.r_sat = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.l_p = 0.
      self.l_i = 0.
      self.l_d = 0.
      self.l_ffwd = 0.
      self.l_stic = 0.
      self.l_sat = 0.
      self.r_p = 0.
      self.r_i = 0.
      self.r_d = 0.
      self.r_ffwd = 0.
      self.r_stic = 0.
      self.r_sat = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_12d.pack(_x.l_p, _x.l_i, _x.l_d, _x.l_ffwd, _x.l_stic, _x.l_sat, _x.r_p, _x.r_i, _x.r_d, _x.r_ffwd, _x.r_stic, _x.r_sat))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 96
      (_x.l_p, _x.l_i, _x.l_d, _x.l_ffwd, _x.l_stic, _x.l_sat, _x.r_p, _x.r_i, _x.r_d, _x.r_ffwd, _x.r_stic, _x.r_sat,) = _struct_12d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_12d.pack(_x.l_p, _x.l_i, _x.l_d, _x.l_ffwd, _x.l_stic, _x.l_sat, _x.r_p, _x.r_i, _x.r_d, _x.r_ffwd, _x.r_stic, _x.r_sat))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 96
      (_x.l_p, _x.l_i, _x.l_d, _x.l_ffwd, _x.l_stic, _x.l_sat, _x.r_p, _x.r_i, _x.r_d, _x.r_ffwd, _x.r_stic, _x.r_sat,) = _struct_12d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_12d = struct.Struct("<12d")
